// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RoboWarX.GTK {
    
    
    public partial class ArenaWidget {
        
        private Gtk.DrawingArea view;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget RoboWarX.GTK.ArenaWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "RoboWarX.GTK.ArenaWidget";
            // Container child RoboWarX.GTK.ArenaWidget.Gtk.Container+ContainerChild
            this.view = new Gtk.DrawingArea();
            this.view.WidthRequest = 300;
            this.view.HeightRequest = 300;
            this.view.Name = "view";
            this.Add(this.view);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.Realized += new System.EventHandler(this.OnRealized);
            this.Unrealized += new System.EventHandler(this.OnUnrealized);
            this.view.ExposeEvent += new Gtk.ExposeEventHandler(this.OnViewExposeEvent);
        }
    }
}
