// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RoboWarX.GTK {
    
    
    public partial class BasicActions {
        
        private Gtk.Action OpenAction;
        
        private Gtk.Action QuitAction;
        
        private Gtk.Action FileMenuAction;
        
        private Gtk.Action NewAction;
        
        private Gtk.Action PlayAction;
        
        private Gtk.Action PauseAction;
        
        public virtual void Build() {
            // Action group RoboWarX.GTK.BasicActions
            this.OpenAction = new Gtk.Action("OpenAction", Mono.Unix.Catalog.GetString("_Open..."), null, "gtk-open");
            this.OpenAction.ShortLabel = Mono.Unix.Catalog.GetString("_Open...");
            this.Add(this.OpenAction, null);
            this.QuitAction = new Gtk.Action("QuitAction", Mono.Unix.Catalog.GetString("_Quit"), null, "gtk-quit");
            this.QuitAction.ShortLabel = Mono.Unix.Catalog.GetString("_Quit");
            this.Add(this.QuitAction, null);
            this.FileMenuAction = new Gtk.Action("FileMenuAction", Mono.Unix.Catalog.GetString("_File"), null, null);
            this.FileMenuAction.ShortLabel = Mono.Unix.Catalog.GetString("_File");
            this.Add(this.FileMenuAction, null);
            this.NewAction = new Gtk.Action("NewAction", Mono.Unix.Catalog.GetString("_Reset"), null, "gtk-refresh");
            this.NewAction.ShortLabel = Mono.Unix.Catalog.GetString("_Reset");
            this.Add(this.NewAction, null);
            this.PlayAction = new Gtk.Action("PlayAction", Mono.Unix.Catalog.GetString("_Play"), null, "gtk-media-play");
            this.PlayAction.ShortLabel = Mono.Unix.Catalog.GetString("_Play");
            this.Add(this.PlayAction, null);
            this.PauseAction = new Gtk.Action("PauseAction", Mono.Unix.Catalog.GetString("_Pause"), null, "gtk-media-pause");
            this.PauseAction.ShortLabel = Mono.Unix.Catalog.GetString("_Pause");
            this.Add(this.PauseAction, null);
        }
    }
}
