// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RoboWarX.GTK {
    
    
    public partial class ErrorDialog {
        
        private Gtk.HBox hbox2;
        
        private Gtk.Image image2;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Label titlelabel;
        
        private Gtk.Label errorlabel;
        
        private Gtk.Button buttonJump;
        
        private Gtk.Button buttonStop;
        
        private Gtk.Button buttonClose;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget RoboWarX.GTK.ErrorDialog
            this.Name = "RoboWarX.GTK.ErrorDialog";
            this.Title = Mono.Unix.Catalog.GetString("Robot error");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Modal = true;
            this.HasSeparator = false;
            // Internal child RoboWarX.GTK.ErrorDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 12;
            this.hbox2.BorderWidth = ((uint)(7));
            // Container child hbox2.Gtk.Box+BoxChild
            this.image2 = new Gtk.Image();
            this.image2.Name = "image2";
            this.image2.Yalign = 0F;
            this.image2.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-dialog-error", Gtk.IconSize.Dialog, 48);
            this.hbox2.Add(this.image2);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox2[this.image2]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.titlelabel = new Gtk.Label();
            this.titlelabel.Name = "titlelabel";
            this.titlelabel.Xalign = 0F;
            this.titlelabel.LabelProp = Mono.Unix.Catalog.GetString("<big><b>Error in robot 'Name'</b></big>");
            this.titlelabel.UseMarkup = true;
            this.vbox3.Add(this.titlelabel);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox3[this.titlelabel]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.errorlabel = new Gtk.Label();
            this.errorlabel.Name = "errorlabel";
            this.errorlabel.Xalign = 0F;
            this.errorlabel.Yalign = 0F;
            this.errorlabel.LabelProp = Mono.Unix.Catalog.GetString("Error text");
            this.errorlabel.UseMarkup = true;
            this.vbox3.Add(this.errorlabel);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox3[this.errorlabel]));
            w4.Position = 1;
            this.hbox2.Add(this.vbox3);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this.vbox3]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            w1.Add(this.hbox2);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(w1[this.hbox2]));
            w6.Position = 0;
            // Internal child RoboWarX.GTK.ErrorDialog.ActionArea
            Gtk.HButtonBox w7 = this.ActionArea;
            w7.Name = "dialog1_ActionArea";
            w7.Spacing = 6;
            w7.BorderWidth = ((uint)(5));
            w7.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonJump = new Gtk.Button();
            this.buttonJump.Sensitive = false;
            this.buttonJump.CanDefault = true;
            this.buttonJump.CanFocus = true;
            this.buttonJump.Name = "buttonJump";
            this.buttonJump.UseStock = true;
            this.buttonJump.UseUnderline = true;
            this.buttonJump.Label = "gtk-jump-to";
            this.AddActionWidget(this.buttonJump, -10);
            Gtk.ButtonBox.ButtonBoxChild w8 = ((Gtk.ButtonBox.ButtonBoxChild)(w7[this.buttonJump]));
            w8.Expand = false;
            w8.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonStop = new Gtk.Button();
            this.buttonStop.CanFocus = true;
            this.buttonStop.Name = "buttonStop";
            this.buttonStop.UseStock = true;
            this.buttonStop.UseUnderline = true;
            this.buttonStop.Label = "gtk-stop";
            this.AddActionWidget(this.buttonStop, -6);
            Gtk.ButtonBox.ButtonBoxChild w9 = ((Gtk.ButtonBox.ButtonBoxChild)(w7[this.buttonStop]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonClose = new Gtk.Button();
            this.buttonClose.CanDefault = true;
            this.buttonClose.CanFocus = true;
            this.buttonClose.Name = "buttonClose";
            this.buttonClose.UseStock = true;
            this.buttonClose.UseUnderline = true;
            this.buttonClose.Label = "gtk-close";
            this.AddActionWidget(this.buttonClose, -7);
            Gtk.ButtonBox.ButtonBoxChild w10 = ((Gtk.ButtonBox.ButtonBoxChild)(w7[this.buttonClose]));
            w10.Position = 2;
            w10.Expand = false;
            w10.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 352;
            this.DefaultHeight = 137;
            this.Show();
            this.buttonStop.Clicked += new System.EventHandler(this.OnButtonStopClicked);
            this.buttonClose.Clicked += new System.EventHandler(this.OnButtonCloseClicked);
        }
    }
}
