// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RoboWarX.GTK {
    
    
    public partial class BasicActions {
        
        private Gtk.Action OpenAction;
        
        private Gtk.Action QuitAction;
        
        private Gtk.Action FileMenuAction;
        
        private Gtk.Action NewAction;
        
        private Gtk.Action PlayAction;
        
        private Gtk.Action PauseAction;
        
        public virtual void Build() {
            // Action group RoboWarX.GTK.BasicActions
            this.OpenAction = new Gtk.Action("OpenAction", "_Open...", null, "gtk-open");
            this.OpenAction.ShortLabel = "_Open...";
            this.Add(this.OpenAction, null);
            this.QuitAction = new Gtk.Action("QuitAction", "_Quit", null, "gtk-quit");
            this.QuitAction.ShortLabel = "_Quit";
            this.Add(this.QuitAction, null);
            this.FileMenuAction = new Gtk.Action("FileMenuAction", "_File", null, null);
            this.FileMenuAction.ShortLabel = "_File";
            this.Add(this.FileMenuAction, null);
            this.NewAction = new Gtk.Action("NewAction", "_Reset", null, "gtk-refresh");
            this.NewAction.ShortLabel = "_Reset";
            this.Add(this.NewAction, null);
            this.PlayAction = new Gtk.Action("PlayAction", "_Play", null, "gtk-media-play");
            this.PlayAction.ShortLabel = "_Play";
            this.Add(this.PlayAction, null);
            this.PauseAction = new Gtk.Action("PauseAction", "_Pause", null, "gtk-media-pause");
            this.PauseAction.ShortLabel = "_Pause";
            this.Add(this.PauseAction, null);
        }
    }
}
