// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RoboWarX.GTK {
    
    
    public partial class RobotWidget {
        
        private Gtk.HBox hbox1;
        
        private Gtk.DrawingArea iconbox;
        
        private Gtk.Label namelabel;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label statuslabel1;
        
        private Gtk.Label statuslabel2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget RoboWarX.GTK.RobotWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "RoboWarX.GTK.RobotWidget";
            // Container child RoboWarX.GTK.RobotWidget.Gtk.Container+ContainerChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.iconbox = new Gtk.DrawingArea();
            this.iconbox.WidthRequest = 32;
            this.iconbox.HeightRequest = 32;
            this.iconbox.Name = "iconbox";
            this.hbox1.Add(this.iconbox);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.iconbox]));
            w1.Position = 0;
            w1.Expand = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.namelabel = new Gtk.Label();
            this.namelabel.Name = "namelabel";
            this.namelabel.Xalign = 0F;
            this.namelabel.LabelProp = Mono.Unix.Catalog.GetString("<big><b>Name</b></big>");
            this.namelabel.UseMarkup = true;
            this.hbox1.Add(this.namelabel);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.namelabel]));
            w2.Position = 1;
            // Container child hbox1.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 12;
            // Container child hbox2.Gtk.Box+BoxChild
            this.statuslabel1 = new Gtk.Label();
            this.statuslabel1.Name = "statuslabel1";
            this.statuslabel1.Xalign = 1F;
            this.statuslabel1.LabelProp = Mono.Unix.Catalog.GetString("Status:\nStatus:");
            this.statuslabel1.Justify = ((Gtk.Justification)(1));
            this.hbox2.Add(this.statuslabel1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox2[this.statuslabel1]));
            w3.Position = 0;
            w3.Expand = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.statuslabel2 = new Gtk.Label();
            this.statuslabel2.Name = "statuslabel2";
            this.statuslabel2.Xalign = 1F;
            this.statuslabel2.LabelProp = Mono.Unix.Catalog.GetString("___\n___");
            this.statuslabel2.Justify = ((Gtk.Justification)(1));
            this.hbox2.Add(this.statuslabel2);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox2[this.statuslabel2]));
            w4.Position = 1;
            this.hbox1.Add(this.hbox2);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.hbox2]));
            w5.PackType = ((Gtk.PackType)(1));
            w5.Position = 2;
            w5.Expand = false;
            this.Add(this.hbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.iconbox.ExposeEvent += new Gtk.ExposeEventHandler(this.OnIconboxExposeEvent);
        }
    }
}
